/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.program;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.awt.event.KeyEvent;
/**
 *
 * @author USER
 */
public class Prodi extends javax.swing.JFrame {

    /**
     * Creates new form Prodi
     */
    public Prodi() {
        initComponents();
         this.setLocationRelativeTo(null);
         //Menampilkan data saat form dibuka
         this.addWindowListener(new java.awt.event.WindowAdapter() {
             public void windowOpened(java.awt.event.WindowEvent evt){
             tampilDataKeTabel();
             }
         });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        KODE_PRODI = new javax.swing.JTextField();
        NAMA_PRODI = new javax.swing.JTextField();
        JUMLAH_DOSEN = new javax.swing.JTextField();
        SIMPAN = new javax.swing.JButton();
        PESAN = new javax.swing.JLabel();
        PASSWORD = new javax.swing.JPasswordField();
        BACK = new javax.swing.JButton();
        TOMBOL_UBAH = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABEL = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("TAMBAH DATA PRODI");

        jLabel2.setText("Kode Prodi :");

        jLabel3.setText("Nama Prodi :");

        jLabel4.setText("Password : ");

        jLabel5.setText("Jumlah Dosen : ");

        KODE_PRODI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KODE_PRODIMouseEntered(evt);
            }
        });
        KODE_PRODI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KODE_PRODIActionPerformed(evt);
            }
        });
        KODE_PRODI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KODE_PRODIKeyPressed(evt);
            }
        });

        NAMA_PRODI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMA_PRODIActionPerformed(evt);
            }
        });

        SIMPAN.setBackground(new java.awt.Color(51, 255, 51));
        SIMPAN.setText("SIMPAN");
        SIMPAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SIMPANMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SIMPANMouseExited(evt);
            }
        });
        SIMPAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIMPANActionPerformed(evt);
            }
        });

        PESAN.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDActionPerformed(evt);
            }
        });

        BACK.setBackground(new java.awt.Color(255, 0, 0));
        BACK.setText("<<BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        TOMBOL_UBAH.setBackground(new java.awt.Color(255, 255, 153));
        TOMBOL_UBAH.setText("UBAH");
        TOMBOL_UBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOMBOL_UBAHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PESAN, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(391, 391, 391))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(KODE_PRODI, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(PASSWORD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NAMA_PRODI, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JUMLAH_DOSEN, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(SIMPAN)
                        .addGap(18, 18, 18)
                        .addComponent(TOMBOL_UBAH)
                        .addGap(18, 18, 18)
                        .addComponent(BACK))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(KODE_PRODI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NAMA_PRODI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JUMLAH_DOSEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SIMPAN)
                    .addComponent(BACK)
                    .addComponent(TOMBOL_UBAH))
                .addGap(35, 35, 35)
                .addComponent(PESAN)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        TABEL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE PRODI", "NAMA PRODI", "PASSWORD", "JUMLAH DOSEN"
            }
        ));
        jScrollPane1.setViewportView(TABEL);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("TABEL PRODI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KODE_PRODIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KODE_PRODIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KODE_PRODIActionPerformed

    private void KODE_PRODIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KODE_PRODIMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_KODE_PRODIMouseEntered

    private void SIMPANMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIMPANMouseEntered
        // TODO add your handling code here:
        PESAN.setText("Klik untuk menyimpan!");
    }//GEN-LAST:event_SIMPANMouseEntered

    private void SIMPANMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SIMPANMouseExited
        // TODO add your handling code here:
        PESAN.setText("");
    }//GEN-LAST:event_SIMPANMouseExited

    private void SIMPANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIMPANActionPerformed
       
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Prodi.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        Connection c =null;
        
        try {
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/unpam", "root" , "");
            System.out.println("Koneksi Berhasil");
        } catch (SQLException ex) {
            Logger.getLogger(Prodi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        Statement st = null;
        try {
            st = c.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Prodi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
           
        // TODO add your handling code here:
        String kodeprodi = KODE_PRODI.getText();
        String namaprodi = NAMA_PRODI.getText();
        char [] password = PASSWORD.getPassword();
        String pass = new String(password); // konversi ke string
        String jumlahdosen = JUMLAH_DOSEN.getText();
        
        //membuat query
        String query = "INSERT INTO prodi VALUES ('" + kodeprodi + "','" + namaprodi + "','" + password + "','" + jumlahdosen + "')";
        
        
        if (kodeprodi.isEmpty()) {
        JOptionPane.showMessageDialog(null,"Kode Prodi Tidak Boleh Kosong!");
        } else if (namaprodi.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nama Prodi Tidak Boleh Kosong!");
        } else if (password.length == 0) {
        JOptionPane.showMessageDialog(null, "Password Tidak Boleh Kosong!");
        } else if (jumlahdosen.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Jumlah Dosen Tidak Boleh Kosong!");
        }else {
        int jmlDosen = 0;
       
        try {
            
        jmlDosen = Integer.parseInt(JUMLAH_DOSEN.getText());
        DefaultTableModel tabel = (DefaultTableModel) TABEL.getModel();
        tabel.addRow(new Object[]{
        KODE_PRODI.getText(),
        NAMA_PRODI.getText(),
        PASSWORD.getPassword(),
        jmlDosen
      
        });
        
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Input harus angka!");
            }
        
            try {
                // execute query
                st.execute(query);
                // Membersikan Field setelah submit data
                KODE_PRODI.setText("");
                NAMA_PRODI.setText("");
                PASSWORD.setText("");
                JUMLAH_DOSEN.setText("");
                
                //memberikan informasi data sudah masuk ke DB
                JOptionPane.showMessageDialog(null, "Data berhasil masuk ke Database");
            } catch (SQLException ex) {
                Logger.getLogger(Prodi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SIMPANActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BACKActionPerformed

    private void NAMA_PRODIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMA_PRODIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMA_PRODIActionPerformed

    private void PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDActionPerformed

    private void KODE_PRODIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KODE_PRODIKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String kodeProdi = KODE_PRODI.getText().trim();
            if (kodeProdi.isEmpty()){
                JOptionPane.showMessageDialog(null, "Silakan masukkan Kode Prodi.");
                return;
            }
            try {
                //membuat koneksi ke database
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/unpam", "root" , "");
                Statement st = c.createStatement();
                
                //menyusun query berdasarkan input dari user
                String query = "SELECT * FROM prodi WHERE kode_prodi = '" + kodeProdi + "'";
                ResultSet rs = st.executeQuery(query);
                
                if (rs.next()) {
                NAMA_PRODI.setText(rs.getString("nama_prodi"));
                PASSWORD.setText(rs.getString("password"));
                JUMLAH_DOSEN.setText(String.valueOf(rs.getInt("jumlah_dosen")));
                JOptionPane.showMessageDialog(null, "Data Ditemukan");
                }else{
                    JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
                }
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan saat mengambil data.");
            }
        }
    }//GEN-LAST:event_KODE_PRODIKeyPressed

    private void TOMBOL_UBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOMBOL_UBAHActionPerformed
        // TODO add your handling code here:
    String kodeProdi = KODE_PRODI.getText();
    String namaProdi = NAMA_PRODI.getText();
    char[] passwordArray = PASSWORD.getPassword();
    String pass = new String(passwordArray);
    String dosenText = JUMLAH_DOSEN.getText();

    // Validasi input
    if (kodeProdi.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Kode Prodi tidak boleh kosong!");
        return;
    } else if (namaProdi.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nama Prodi tidak boleh kosong!");
        return;
    } else if (passwordArray.length == 0) {
        JOptionPane.showMessageDialog(null, "Password tidak boleh kosong!");
        return;
    }

    int jmlDosen;
    try {
        jmlDosen = Integer.parseInt(dosenText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Jumlah Dosen harus berupa angka!");
        return;
    }

    try {
        // Koneksi ke database
        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/unpam", "root", "");
        Statement st = c.createStatement();

        // Cek apakah data dengan kode prodi ada
        String cekQuery = "SELECT * FROM prodi WHERE kode_prodi = '" + kodeProdi + "'";
        ResultSet rs = st.executeQuery(cekQuery);
        if (rs.next()) {
            // Lakukan update
            String updateQuery = "UPDATE prodi SET nama_prodi = '" + namaProdi + "', password = '" + pass + "', jumlah_dosen = '" + jmlDosen + "' WHERE kode_prodi = '" + kodeProdi + "'";
            int result = st.executeUpdate(updateQuery);
            
            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
                
                //Clear field setelah update
                KODE_PRODI.setText("");
                NAMA_PRODI.setText("");
                PASSWORD.setText("");
                JUMLAH_DOSEN.setText("");
                
            } else {
                JOptionPane.showMessageDialog(null, "Gagal mengubah data.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Data dengan kode prodi tersebut tidak ditemukan.");
        }

        // Refresh tabel
        DefaultTableModel model = (DefaultTableModel) TABEL.getModel();
        model.setRowCount(0); // Hapus semua baris lama

        ResultSet rsRefresh = st.executeQuery("SELECT * FROM prodi");
        while (rsRefresh.next()) {
            String kode = rsRefresh.getString("kode_prodi");
            String nama = rsRefresh.getString("nama_prodi");
            String password = rsRefresh.getString("password");
            int jumlah = rsRefresh.getInt("jumlah_dosen");

            model.addRow(new Object[]{kode, nama, password, jumlah});
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
        }
    
    }//GEN-LAST:event_TOMBOL_UBAHActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prodi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prodi().setVisible(true);
            }
        });
    }
    
    private void tampilDataKeTabel(){
        try {
            //menyiapkan koneksi ke database
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/unpam", "root" , "");
            
            //Membuat Statement 
            Statement st = c.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM prodi");
            
            //Mengambil Model dari JTable
            DefaultTableModel model = (DefaultTableModel) TABEL.getModel();
            model.setRowCount(0); //mengosongkan tabel dari data lama agar tidak double saat refresh
            
            //Tambahkan data dari database ke JTable
            while(rs.next()){
                String kode = rs.getString("kode_prodi");
                String nama = rs.getString("nama_prodi");
                String pass = rs.getString("password");
                int jumlah = rs.getInt("jumlah_dosen");
                
                model.addRow(new Object[]{kode, nama, pass, jumlah});
            
            }
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Menampilkan Data!");
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JTextField JUMLAH_DOSEN;
    private javax.swing.JTextField KODE_PRODI;
    private javax.swing.JTextField NAMA_PRODI;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JLabel PESAN;
    private javax.swing.JButton SIMPAN;
    private javax.swing.JTable TABEL;
    private javax.swing.JButton TOMBOL_UBAH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
