/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.program;

/**
 *
 * @author USER
 */
public class utama extends javax.swing.JFrame {

    /**
     * Creates new form utama
     */
    public utama() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        APLIKASI = new javax.swing.JMenu();
        PRODI = new javax.swing.JMenuItem();
        MATA_KULIAH = new javax.swing.JMenuItem();
        DOSEN = new javax.swing.JMenuItem();
        CETAK_NAMA = new javax.swing.JMenuItem();
        APLIKASI_HOTEL = new javax.swing.JMenuItem();
        MASTER = new javax.swing.JMenu();
        DATA = new javax.swing.JMenu();
        JADWAL = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setInheritsPopupMenu(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        APLIKASI.setText("Aplikasi");

        PRODI.setText("Prodi");
        PRODI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRODIActionPerformed(evt);
            }
        });
        APLIKASI.add(PRODI);

        MATA_KULIAH.setText("Mata Kuliah");
        APLIKASI.add(MATA_KULIAH);

        DOSEN.setText("Dosen");
        APLIKASI.add(DOSEN);

        CETAK_NAMA.setText("Cetak Nama");
        CETAK_NAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CETAK_NAMAActionPerformed(evt);
            }
        });
        APLIKASI.add(CETAK_NAMA);

        APLIKASI_HOTEL.setText("Aplikasi Hotel");
        APLIKASI_HOTEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APLIKASI_HOTELActionPerformed(evt);
            }
        });
        APLIKASI.add(APLIKASI_HOTEL);

        jMenuBar1.add(APLIKASI);

        MASTER.setText("Master");
        jMenuBar1.add(MASTER);

        DATA.setText("Data");
        jMenuBar1.add(DATA);

        JADWAL.setText("Jadwal");
        jMenuBar1.add(JADWAL);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PRODIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRODIActionPerformed
        // TODO add your handling code here:
        Prodi p = new Prodi();
        p.setVisible(true);
    }//GEN-LAST:event_PRODIActionPerformed

    private void CETAK_NAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CETAK_NAMAActionPerformed
        // TODO add your handling code here:.
        cInputNama inputNama = new cInputNama();
        inputNama.setVisible(true);
    }//GEN-LAST:event_CETAK_NAMAActionPerformed

    private void APLIKASI_HOTELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APLIKASI_HOTELActionPerformed
        // TODO add your handling code here:
        cAplikasiHotel aplikasiHotel = new cAplikasiHotel();
        aplikasiHotel.setVisible(true);
    }//GEN-LAST:event_APLIKASI_HOTELActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu APLIKASI;
    private javax.swing.JMenuItem APLIKASI_HOTEL;
    private javax.swing.JMenuItem CETAK_NAMA;
    private javax.swing.JMenu DATA;
    private javax.swing.JMenuItem DOSEN;
    private javax.swing.JMenu JADWAL;
    private javax.swing.JMenu MASTER;
    private javax.swing.JMenuItem MATA_KULIAH;
    private javax.swing.JMenuItem PRODI;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
